name=NeuDB
version=1.2.2
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=Ultra-lean, resource-adaptive LSM-Tree storage engine with power-fail safety for ESP32.
paragraph=NeuDB is a high-performance, asynchronous Log-Structured Merge-tree storage engine tailored for write-heavy embedded logging. Utilizing a FreeRTOS background compaction scheduler, real-time adaptive memory auto-tuning (tuneMemtable), integrated Bloom Filters, and Binary Search (std::lower_bound), it minimizes write amplification and slashes read latencies down to microseconds. Features atomic Write-Ahead Logging (WAL) for bulletproof cold crash recovery against sudden power failures.
category=Data Storage
url=https://github.com/ulywae/NeuDB
architectures=esp32, esp32s3, esp32c3
includes=NeuDB.h
