name=NeuDB
version=1.2.0
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=An industrial-grade, ultra-lean LSM-Tree storage engine with power-fail safety for ESP32.
paragraph=NeuDB (NeuLSMDB_FS) is a high-performance, asynchronous Log-Structured Merge-tree storage engine tailored for write-heavy embedded logging. Utilizing a FreeRTOS background compaction scheduler, integrated Bloom Filters, and Binary Search (std::lower_bound), it reduces storage write amplification and slashes read latencies down to microseconds. Features atomic Write-Ahead Logging (WAL) for bulletproof crash recovery against sudden power failures on Flash memory (LittleFS).
category=Data Storage
url=https://github.com/ulywae/NeuDB
architectures=esp32
includes=NeuDB.h
